version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - NAME=VeX
    volumes:
      - ./data:/app/static/
    restart: on-failure